### ISSUE TITLE
agree on installation standards

### ISSUE THREAD

**Issue by simzacks** [knowabli/edison#22]
Agree on standards and a coding-standards.txt file to the repo.

There are 3 standards that the team needs to agree on, that I see so far:
* how to install pip. You can either do this using the package manager (apt-get) or by downloading it and installing directly. If you install it with the package manager, you cannot call pip install --upgrade.

* how to call pip. either use pip, pip3, or python -m pip, but there should be a standard way of doing this.

* how to install packages - either using a requirements.txt file and other people are putting the pip install directly in the code.

**Comment by naamaCohen1** [comment]
we decided to be like the setup.sh file.
1. we used in apt-get install 
2. we used pip3
3. we used requirements file

**Comment by naamaCohen1** [comment]
we decided to be like the setup.sh file.

we used in apt-get install
we used pip3
we used requirements file
